import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GenerateJokeAI } from "./examples/generate-ui/action";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GenerateJokeAI>
          <div className="px-8">
            <Link href="/">Back</Link>
          </div>
          <div>{children}</div>
        </GenerateJokeAI>
      </body>
    </html>
  );
}
